name: Build and Deploy Lambda Functions

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/build-and-deploy-lambdas.yaml
      - .github/workflows/reusable-build-lambdas.yaml
      - .github/workflows/reusable-deploy-lambdas.yaml
      - lambdas/**

jobs:
  build:
    uses: ./.github/workflows/reusable-build-lambdas.yaml
    with:
      S3_LAMBDA_BUCKET_NAME: ${{ vars.S3_LAMBDA_BUCKET_NAME }}
    secrets:
      AWS_ARN_IAM_ROLE_GITHUB_ACTIONS: ${{ secrets.AWS_ARN_IAM_ROLE_GITHUB_ACTIONS }}

  deploy:
    needs: build
    uses: ./.github/workflows/reusable-deploy-lambdas.yaml
    with:
      S3_LAMBDA_BUCKET_NAME: ${{ vars.S3_LAMBDA_BUCKET_NAME }}
    secrets:
      AWS_ARN_IAM_ROLE_GITHUB_ACTIONS: ${{ secrets.AWS_ARN_IAM_ROLE_GITHUB_ACTIONS }}
