name: Build and Deploy SPA

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/build-and-deploy-spa.yaml
      - .github/workflows/reusable-build-and-deploy-spa.yaml
      - spa/**

jobs:
  build-and-deploy:
    uses: ./.github/workflows/reusable-build-and-deploy-spa.yaml
    with:
      S3_SPA_BUCKET_NAME: ${{ vars.S3_SPA_BUCKET_NAME }}
    secrets:
      AWS_ARN_IAM_ROLE_GITHUB_ACTIONS: ${{ secrets.AWS_ARN_IAM_ROLE_GITHUB_ACTIONS }}
